light:
  phlipsHueIp:
  phlipsHueApiKey:
  phlipsHueRoomName: Biuro
  phlipsHueLightName: Lightstrip
  brightnes: 30
  lightMode: AVAILABLE
  automationFrequencySeconds: 1
window:
  pinned: true
  enablePreviousPosition: true
  positionX:
  positionY:
workingTime:
  days:
    - MONDAY
    - TUESDAY
    - WEDNESDAY
    - THURSDAY
    - FRIDAY
  start: 09:00
  end: 17:00