light:
  phlipsHueIp:
  phlipsHueApiKey:
  phlipsHueRoomName: Biuro
  phlipsHueLightName: Lightstrip
  brightnes: 30
  lightMode: AVAILABLE
  automationFrequencySeconds: 1
imageDetector:
  imageDetectorThreshold: 0.8
  windowsBarStartXPosition: 1400
  windowsBarStartYPosition: 920
  windowsBarWidth: 305
  windowsBarHight: 35
window:
  pinned: true
  positionX:
  positionY:
workingTime:
  days:
    - MONDAY
    - TUESDAY
    - WEDNESDAY
    - THURSDAY
    - FRIDAY
  start: 09:00
  end: 17:00
