light:
  phlipsHueIp:
  phlipsHueApiKey:
  phlipsHueRoomName: Biuro
  phlipsHueLightName: Lightstrip
  brightnes: 30
  lightMode: "WORKING"
  automationFrequencySeconds: 1
window:
  pinned: true
  enablePreviousPosition: false
  positionX: 200
  positionY: 200
workingTime:
  days:
  - "MONDAY"
  - "TUESDAY"
  - "WEDNESDAY"
  - "FRIDAY"
  - "THURSDAY"
  start: "09:00"
  end: "17:00"
